name: Infra ne leli

on:
  push:
    branches:
      - 'feature/**'
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    # Run on PRs and feature branch pushes
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/'))
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan.binary

  terraform-apply:
    # Run only on push to main (i.e., after PR merged)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: terraform-plan
    runs-on: self-hosted
    environment:
      name: dev  # Requires manual approval

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Azure environment variables
        run: |
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
          echo "OBJECT_ID=${{ secrets.OBJECT_ID }}" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID=${{ secrets.SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "TENANT_ID=${{ secrets.TENANT_ID }}" >> $GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          allow-no-subscriptions: true
          auth-type: 'oidc'

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan.binary
