name: Terraform CI/CD

on:
  push:
    branches:
      - 'feature/**'
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/') || github.event_name == 'pull_request'
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Azure environment variables
        run: |
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
          echo "OBJECT_ID=${{ secrets.OBJECT_ID }}" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID=${{ secrets.SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "TENANT_ID=${{ secrets.TENANT_ID }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan.binary

  terraform-apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: terraform-plan
    runs-on: self-hosted
    environment:
      name: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Azure environment variables
        run: |
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
          echo "OBJECT_ID=${{ secrets.OBJECT_ID }}" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID=${{ secrets.SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "TENANT_ID=${{ secrets.TENANT_ID }}" >> $GITHUB_ENV

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan.binary
