name: Terraform Deploy to Azure

on:
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - synchronize
      - reopened

  push:
    branches:
      - 'main'

jobs:
  terraform-plan:
    if: github.event_name == 'pull_request'
    name: Terraform Plan on PR
    runs-on: self-hosted
    timeout-minutes: 20

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - run: terraform init

      - run: terraform validate

      - run: terraform plan

  terraform-apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Terraform Apply after merge to main
    runs-on: self-hosted
    environment: dev   # <--- Manual approval required here (configure environment protection in repo settings)
    timeout-minutes: 30

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - run: terraform init

      - run: terraform plan -out=tfplan

      - run: terraform show tfplan

      - run: terraform apply -auto-approve tfplan
