name: Terraform Deploy to Azure

on:
  push:
    branches:
      - 'feature/**'
      - 'main'

jobs:
  Terraform-validate-plan:
    if: startsWith(github.ref, 'refs/heads/feature/')
    name: Terraform Validate & Plan
    runs-on: self-hosted
    environment: dev
    timeout-minutes: 20

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login 
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Terraform installer
        uses: autero1/action-terraform@v3.0.1
        with:
          terraform-version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          TF_LOG: DEBUG
        run: terraform plan

  Terraform-apply:
    if: github.ref == 'refs/heads/main'
    name: Terraform Apply
    runs-on: self-hosted
    environment: dev   
    timeout-minutes: 30

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login 
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Terraform installer
        uses: autero1/action-terraform@v3.0.1
        with:
          terraform-version: latest
          
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        env:
          TF_LOG: DEBUG
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        env:
          TF_LOG: DEBUG
        run: terraform apply -auto-approve
